  - name: Service
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: svc.yml.j2
    when: WITH_H5P_EDITOR is defined and WITH_H5P_EDITOR|bool
    tags:
      - service

  - name: Configmap
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: configmap.yml.j2
      apply: yes
    when: WITH_H5P_EDITOR is defined and WITH_H5P_EDITOR|bool
    tags:
      - configmap

  - name: Deployment
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: deployment.yml.j2
    when: WITH_H5P_EDITOR is defined and WITH_H5P_EDITOR|bool
    tags:
      - deployment
